version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transfermeit
      MYSQL_USER: transfermeit
      MYSQL_PASSWORD: transfermeit
    ports:
      - "127.0.0.1:3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-proot"]
      timeout: 20s
      retries: 10

  migrate:
    image: migrate/migrate
    network_mode: "host"
    volumes:
      - ./sql:/sql
    command: ["-path", "/sql", "-database", "mysql://transfermeit:transfermeit@tcp(127.0.0.1:3306)/transfermeit", "up"]

  minio:
    image: minio/minio
    ports:
      - "127.0.0.1:9000:9000"
    command: "server /data{1...4}"
    environment:
      MINIO_ACCESS_KEY: FfizvUST5eqWY0jhAulGKcIdLOz09VyvfE5
      MINIO_SECRET_KEY: lhFC48WhyPqVPiQJvthIbdj22KnturqaayT

  redis:
    image: "redis:alpine"
    ports:
      - "127.0.0.1:6379:6379"

  app:
    build:
      context: .
    environment:
      DB_HOST: root:root@tcp(db:3306)/transfermeit
      SERVER_KEY: QVcnKozlSUvRSPj0jqjya7vZJLrkKUvKIq0WkpKN
      SESSION_KEY: rps2P8irs0mT5uCgicv8m5PMq9a6WyzbxL7HWeRK
      REDIS_HOST: "redis:6379"
      MINIO_ACCESS_KEY: FfizvUST5eqWY0jhAulGKcIdLOz09VyvfE5
      MINIO_SECRET_KEY: lhFC48WhyPqVPiQJvthIbdj22KnturqaayT
      MINIO_ENDPOINT: "minio:9000"
      COLLECTOR_HOSTNAME: jaeger:14268
    depends_on:
      - db
      - minio
    links:
      - db
      - redis
      - minio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transfermeit.rule=Host(`localhost`)"
      - "traefik.http.routers.transfermeit.entrypoints=web"
      - "traefik.http.services.transfermeit.loadbalancer.server.port=8080"

  traefik:
    image: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--tracing=true"
      - "--tracing.serviceName=traefik"
      - "--tracing.jaeger.samplingServerURL=http://jaeger:5778/sampling"
      - "--tracing.jaeger.collector.endpoint=http://jaeger:14268/api/traces?format=zipkin.thrift"
      - "--tracing.jaeger.gen128Bit"
      - "--tracing.jaeger.propagation=b3"
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - jaeger
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "127.0.0.1:16686:16686"
      - "127.0.0.1:14268:14268"
    environment:
      JAEGER_REPORTER_LOG_SPANS: "true"
    command:
      - "--log-level=debug"