version: '3.1'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transfermeit
      MYSQL_USER: transfermeit
      MYSQL_PASSWORD: transfermeit
    container_name: transfermeit-backend-db
    ports:
      - "127.0.0.1:3306:3306" # added local exposed ports for migration script
    tty: true
    restart: always

  app:
    build:
      context: .
    restart: always
    environment:
      db: transfermeit:transfermeit@tcp(db:3306)/transfermeit
      sentry_dsn: ${sentry_dsn:?err}
      server_key: ${server_key:?err}
      session_key: ${session_key:?err}
      file_dir: ${file_dir:-/var/tmp/transfermeit/}
    tty: true
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db