version: '3.1'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transfermeit
      MYSQL_USER: transfermeit
      MYSQL_PASSWORD: transfermeit
    container_name: transfermeit-backend-db
    ports:
      - "3306:3306"
    tty: true
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/:ro
    restart: always

  app:
    build:
      context: .
    container_name: transfermeit-backend
    restart: always
    environment:
      db: transfermeit:transfermeit@tcp(db:3306)/transfermeit
      sentry_dsn: ${sentry_dsn}
      server_key: ${server_key}
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db