version: '3.8'
services:
  app:
    image: maxisme/transfermeit-backend:${TAG:?err}
    env_file:
      - "${ENV_FILE:?err}"
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.transfermeit-backend.rule=Host(`${SUBDOM}sock.transferme.it`)"
        - "traefik.http.routers.transfermeit-backend.entrypoints=web-secure"
        - "traefik.http.routers.transfermeit-backend.tls.certresolver=letsencrypt"
        - "traefik.http.routers.transfermeit-backend.middlewares=404"
        - "traefik.http.services.transfermeit-backend.loadbalancer.server.port=8080"
    networks:
      - traefik
      - db
      - logging
      - tracing

  migrate:
    image: migrate/migrate
    networks:
      - db
    command: ["-source", "${MIGRATE_SRC:?err}", "-database", "mysql://${DB_HOST:?err}", "up"]
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: none

networks:
  traefik:
    external: true
  db:
    external: true
  logging:
    external: true
  tracing:
    external: true
  minio_tmi:
    driver: overlay