name: Transfer Me It
on: [push]

jobs:
  test:
    name: Test with version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.12', '1.13']
    steps:
      - uses: actions/checkout@master

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Fetch cached dependencies
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        env:
          session_key: "UH9ax500yN4mnTO60WLY2ae943tsqzFw"
          db: "root:root@"
        run: go test -v

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: github
          key: ${{ secrets.KEY }}
          script: |
            sudo /root/transfermeit-backend/deploy.sh ${{ github.sha }}